graph: dd_graph
loading_config:
  data_source:
    scheme: odps  # file, oss, s3, hdfs; only file is supported now
  import_option: init # append, overwrite, only init is supported now
  format:
    type: arrow
    metadata:
      batch_reader: false
      batch_size: 16MB
vertex_mappings:
  - type_name: User  # must align with the schema
    inputs:
      - grape_dev/user_node
    column_mappings:
      - column:
          index: 0    # can be omitted if the index is the same as the property index
          name: ding_user_id  # can be omitted if the name is not known
        property: id
      - column:
          index: 2
          name: city_last_visit
        property: city
      - column:
          index: 3
          name: role_name
        property: roleName
      - column:
          index: 4
          name: act_usr_days_1m
        property: activeDays
      - column:
          index: 5
          name: org_industry_sub_id
        property: subIndustry
edge_mappings:
  - type_triplet:
      edge: Friend
      source_vertex: User
      destination_vertex: User
    inputs:
      - grape_dev/user_friend_edge
    source_vertex_mappings:
      - column:
          index: 0
          name: ding_user_id
        property: id
    destination_vertex_mappings:
      - column:
          index: 1
          name: friend_user_id
        property: id
